server:
  port: 8189
  servlet:
    context-path: /book_market

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_book_market?currentSchema=book_market
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
        schema_update:
          unique_constrains_strategy: RECREATE_QUIETLY
logging:
  file:
    path: logs
  level:
    root: info
    org:
      springframework:
        web: debug
        hibernate: error
        data: error
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'

