server:
  port: 8190

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#spring:
#  cloud:
#    config:
#      uri: http://localhost:8081
#      username: root
#      password: s3cr3t
#      name: conf
