spring:
  application:
    name: eureka-client-books
    servlet:
      context-path: /
  datasource:
    url: jdbc:postgresql://localhost:5432/db_book_market?currentSchema=book_market
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
          temp:
            use_jdbc_metadata_defaults: false
          schema_update:
            unique_constrains_strategy: RECREATE_QUIETLY
server:
  port: 8191
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8190/eureka}
    fetchRegistry: true
